/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pesqsat;

//import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author cpd
 */
public class Terminal extends javax.swing.JFrame {

    /**
     * Creates new form Terminal
     */
    public Terminal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPainel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlLogo = new javax.swing.JLabel();
        jlPergunta1 = new javax.swing.JLabel();
        jlPergunta2 = new javax.swing.JLabel();
        jlBom = new javax.swing.JLabel();
        jbBom = new javax.swing.JButton();
        jlRegular = new javax.swing.JLabel();
        jbRegular = new javax.swing.JButton();
        jlRuim = new javax.swing.JLabel();
        jbRuim = new javax.swing.JButton();
        jlSim = new javax.swing.JLabel();
        jbSim = new javax.swing.JButton();
        jlNao = new javax.swing.JLabel();
        jbNao = new javax.swing.JButton();
        jbEnviar = new javax.swing.JButton();
        jlRodape = new javax.swing.JLabel();
        jlFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesquisa de Satisfação");
        setAlwaysOnTop(true);
        setExtendedState(6);
        setName("Terminal"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(null);

        jPainel.setBackground(new java.awt.Color(0, 0, 0));
        jPainel.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPainel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pesquisa de Satisfação");
        jPainel.add(jLabel1);
        jLabel1.setBounds(30, 80, 534, 56);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Pesquisa de Satisfação");
        jPainel.add(jLabel2);
        jLabel2.setBounds(33, 83, 534, 56);

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesqsat/logoIESI.png"))); // NOI18N
        jPainel.add(jlLogo);
        jlLogo.setBounds(800, 80, 186, 52);

        jlPergunta1.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        jlPergunta1.setForeground(new java.awt.Color(255, 255, 255));
        jlPergunta1.setText("Como foi o atendimento?");
        jPainel.add(jlPergunta1);
        jlPergunta1.setBounds(30, 270, 286, 30);

        jlPergunta2.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        jlPergunta2.setForeground(new java.awt.Color(255, 255, 255));
        jlPergunta2.setText("Como foi o atendimento?");
        jPainel.add(jlPergunta2);
        jlPergunta2.setBounds(30, 460, 286, 30);

        jlBom.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        jlBom.setForeground(new java.awt.Color(255, 255, 255));
        jlBom.setText("Bom");
        jPainel.add(jlBom);
        jlBom.setBounds(430, 270, 53, 30);

        jbBom.setBackground(new java.awt.Color(0, 0, 0));
        jbBom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesqsat/bom.gif"))); // NOI18N
        jbBom.setBorder(null);
        jbBom.setContentAreaFilled(false);
        jbBom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbBom.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pesqsat/bomPress.gif"))); // NOI18N
        jbBom.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pesqsat/bomOpaco.gif"))); // NOI18N
        jbBom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBomActionPerformed(evt);
            }
        });
        jPainel.add(jbBom);
        jbBom.setBounds(350, 250, 65, 65);

        jlRegular.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        jlRegular.setForeground(new java.awt.Color(255, 255, 255));
        jlRegular.setText("Regular");
        jPainel.add(jlRegular);
        jlRegular.setBounds(680, 270, 100, 30);

        jbRegular.setBackground(new java.awt.Color(0, 0, 0));
        jbRegular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesqsat/regular.gif"))); // NOI18N
        jbRegular.setBorder(null);
        jbRegular.setContentAreaFilled(false);
        jbRegular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbRegular.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pesqsat/regularPress.gif"))); // NOI18N
        jbRegular.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pesqsat/regularOpaco.gif"))); // NOI18N
        jbRegular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegularActionPerformed(evt);
            }
        });
        jPainel.add(jbRegular);
        jbRegular.setBounds(600, 250, 65, 65);

        jlRuim.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        jlRuim.setForeground(new java.awt.Color(255, 255, 255));
        jlRuim.setText("Ruim");
        jPainel.add(jlRuim);
        jlRuim.setBounds(930, 270, 70, 30);

        jbRuim.setBackground(new java.awt.Color(0, 0, 0));
        jbRuim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesqsat/ruim.gif"))); // NOI18N
        jbRuim.setBorder(null);
        jbRuim.setContentAreaFilled(false);
        jbRuim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbRuim.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pesqsat/ruimPress.gif"))); // NOI18N
        jbRuim.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pesqsat/ruimOpaco.gif"))); // NOI18N
        jbRuim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRuimActionPerformed(evt);
            }
        });
        jPainel.add(jbRuim);
        jbRuim.setBounds(850, 250, 65, 65);

        jlSim.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        jlSim.setForeground(new java.awt.Color(255, 255, 255));
        jlSim.setText("Sim");
        jPainel.add(jlSim);
        jlSim.setBounds(430, 460, 45, 30);

        jbSim.setBackground(new java.awt.Color(0, 0, 0));
        jbSim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesqsat/bom.gif"))); // NOI18N
        jbSim.setBorder(null);
        jbSim.setContentAreaFilled(false);
        jbSim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSim.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pesqsat/bomPress.gif"))); // NOI18N
        jbSim.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pesqsat/bomOpaco.gif"))); // NOI18N
        jbSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSimActionPerformed(evt);
            }
        });
        jPainel.add(jbSim);
        jbSim.setBounds(350, 440, 65, 65);

        jlNao.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        jlNao.setForeground(new java.awt.Color(255, 255, 255));
        jlNao.setText("Não");
        jPainel.add(jlNao);
        jlNao.setBounds(680, 460, 100, 30);

        jbNao.setBackground(new java.awt.Color(0, 0, 0));
        jbNao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesqsat/ruim.gif"))); // NOI18N
        jbNao.setBorder(null);
        jbNao.setContentAreaFilled(false);
        jbNao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbNao.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pesqsat/ruimPress.gif"))); // NOI18N
        jbNao.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pesqsat/ruimOpaco.gif"))); // NOI18N
        jbNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNaoActionPerformed(evt);
            }
        });
        jPainel.add(jbNao);
        jbNao.setBounds(600, 440, 65, 65);

        jbEnviar.setBackground(new java.awt.Color(0, 0, 0));
        jbEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesqsat/EnviarInformacoes.gif"))); // NOI18N
        jbEnviar.setContentAreaFilled(false);
        jbEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbEnviar.setPreferredSize(new java.awt.Dimension(260, 44));
        jbEnviar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pesqsat/EnviarInformacoesPress.gif"))); // NOI18N
        jbEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnviarActionPerformed(evt);
            }
        });
        jPainel.add(jbEnviar);
        jbEnviar.setBounds(380, 560, 260, 44);

        jlRodape.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        jlRodape.setForeground(new java.awt.Color(255, 255, 255));
        jlRodape.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlRodape.setText("Sua opinião é muito importante para nós. Participe! É rápido e fácil.");
        jPainel.add(jlRodape);
        jlRodape.setBounds(0, 660, 1020, 30);

        jlFundo.setBackground(new java.awt.Color(0, 0, 0));
        jlFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesqsat/bg.jpg"))); // NOI18N
        jPainel.add(jlFundo);
        jlFundo.setBounds(-6, 0, 1030, 768);

        getContentPane().add(jPainel);
        jPainel.setBounds(0, 0, 1024, 768);

        setSize(new java.awt.Dimension(1235, 719));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbBomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBomActionPerformed
        jbBom.setSelected(false);
        jbRegular.setSelected(true);
        jbRuim.setSelected(true);
    }//GEN-LAST:event_jbBomActionPerformed

    private void jbRegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegularActionPerformed
        jbBom.setSelected(true);
        jbRegular.setSelected(false);
        jbRuim.setSelected(true);
    }//GEN-LAST:event_jbRegularActionPerformed

    private void jbRuimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRuimActionPerformed
        jbBom.setSelected(true);
        jbRegular.setSelected(true);
        jbRuim.setSelected(false);
    }//GEN-LAST:event_jbRuimActionPerformed

    private void jbSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSimActionPerformed
        jbSim.setSelected(false);
        jbNao.setSelected(true);
    }//GEN-LAST:event_jbSimActionPerformed

    private void jbNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNaoActionPerformed
        jbSim.setSelected(true);
        jbNao.setSelected(false);
    }//GEN-LAST:event_jbNaoActionPerformed

    private void jbEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnviarActionPerformed
        //Verifica conexão.
        try {
            
        } catch (Exception e) {
        }
        
        //Verifica Seleções
        
        
        //Reseta a tela.
        Terminal.this.setAlwaysOnTop(false);
        JOptionPane.showMessageDialog(this, "Obrigado por participar!");
        Terminal.this.setAlwaysOnTop(true);
        jbBom.setSelected(false);
        jbRegular.setSelected(false);
        jbRuim.setSelected(false);
        jbSim.setSelected(false);
        jbNao.setSelected(false);
    }//GEN-LAST:event_jbEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //tenta se conectar ao bd.
        Banco db = new Banco();
        boolean ok = db.abrir();
        if (ok) {
            JOptionPane.showMessageDialog(null, "Bem vindo!");
        } else {
            System.exit(0);
        }
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Terminal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPainel;
    private javax.swing.JButton jbBom;
    private javax.swing.JButton jbEnviar;
    private javax.swing.JButton jbNao;
    private javax.swing.JButton jbRegular;
    private javax.swing.JButton jbRuim;
    private javax.swing.JButton jbSim;
    private javax.swing.JLabel jlBom;
    private javax.swing.JLabel jlFundo;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlNao;
    private javax.swing.JLabel jlPergunta1;
    private javax.swing.JLabel jlPergunta2;
    private javax.swing.JLabel jlRegular;
    private javax.swing.JLabel jlRodape;
    private javax.swing.JLabel jlRuim;
    private javax.swing.JLabel jlSim;
    // End of variables declaration//GEN-END:variables
}
